HayvanSahiplenme/Controllers/CinsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HayvanSahiplenme.Data;
using HayvanSahiplenme.Models;
using Microsoft.AspNetCore.Authorization;

namespace HayvanSahiplenme.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CinsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CinsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Cins
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Cins.Include(c => c.Tur);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Cins/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cins = await _context.Cins
                .Include(c => c.Tur)
                .FirstOrDefaultAsync(m => m.CinsId == id);
            if (cins == null)
            {
                return NotFound();
            }

            return View(cins);
        }

        // GET: Cins/Create
        public IActionResult Create()
        {
            ViewData["TurId"] = new SelectList(_context.Tur, "TurId", "TurAd");
            return View();
        }

        // POST: Cins/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CinsId,CinsAd,CinsAdIng,TurId")] Cins cins)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cins);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["TurId"] = new SelectList(_context.Tur, "TurId", "TurAd", cins.TurId);
            return View(cins);
        }

        // GET: Cins/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cins = await _context.Cins.FindAsync(id);
            if (cins == null)
            {
                return NotFound();
            }
            ViewData["TurId"] = new SelectList(_context.Tur, "TurId", "TurAd", cins.TurId);
            return View(cins);
        }

        // POST: Cins/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CinsId,CinsAd,CinsAdIng,TurId")] Cins cins)
        {
            if (id != cins.CinsId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cins);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CinsExists(cins.CinsId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TurId"] = new SelectList(_context.Tur, "TurId", "TurAd", cins.TurId);
            return View(cins);
        }

        // GET: Cins/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cins = await _context.Cins
                .Include(c => c.Tur)
                .FirstOrDefaultAsync(m => m.CinsId == id);
            if (cins == null)
            {
                return NotFound();
            }

            return View(cins);
        }

        // POST: Cins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cins = await _context.Cins.FindAsync(id);
            _context.Cins.Remove(cins);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CinsExists(int id)
        {
            return _context.Cins.Any(e => e.CinsId == id);
        }
    }
}

HayvanSahiplenme/Controllers/TursController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HayvanSahiplenme.Data;
using HayvanSahiplenme.Models;
using Microsoft.AspNetCore.Authorization;

namespace HayvanSahiplenme.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TursController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TursController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Turs
       
        public async Task<IActionResult> Index()
        {
            return View(await _context.Tur.ToListAsync());
        }

        // GET: Turs/Details/5
        
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tur = await _context.Tur
                .FirstOrDefaultAsync(m => m.TurId == id);
            if (tur == null)
            {
                return NotFound();
            }

            return View(tur);
        }

        // GET: Turs/Create
        
        public IActionResult Create()
        {
            return View();
        }

        // POST: Turs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public async Task<IActionResult> Create([Bind("TurId,TurAd,TurAdIng")] Tur tur)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tur);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tur);
        }

        // GET: Turs/Edit/5
        
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tur = await _context.Tur.FindAsync(id);
            if (tur == null)
            {
                return NotFound();
            }
            return View(tur);
        }

        // POST: Turs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public async Task<IActionResult> Edit(int id, [Bind("TurId,TurAd,TurAdIng")] Tur tur)
        {
            if (id != tur.TurId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tur);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TurExists(tur.TurId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tur);
        }

        // GET: Turs/Delete/5
        
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tur = await _context.Tur
                .FirstOrDefaultAsync(m => m.TurId == id);
            if (tur == null)
            {
                return NotFound();
            }

            return View(tur);
        }

        // POST: Turs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tur = await _context.Tur.FindAsync(id);
            _context.Tur.Remove(tur);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TurExists(int id)
        {
            return _context.Tur.Any(e => e.TurId == id);
        }
    }
}

HayvanSahiplenme/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HayvanSahiplenme</title>
    <!-- Owl Carousel
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Rokkitt:100,300,400,700" rel="stylesheet">

    <!-- Animate.css -->
    <link rel="stylesheet" href="~/css/animate.css">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="~/css/icomoon.css">
    <!-- Ion Icon Fonts-->
    <link rel="stylesheet" href="~/css/ionicons.min.css">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css">

    <!-- Magnific Popup -->
    <link rel="stylesheet" href="~/css/magnific-popup.css">

    <!-- Flexslider  -->
    <link rel="stylesheet" href="~/css/flexslider.css">

    <!-- Owl Carousel -->
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/owl.theme.default.min.css">

    <!-- Date Picker -->
    <link rel="stylesheet" href="~/css/bootstrap-datepicker.css">
    <!-- Flaticons  -->
    <link rel="stylesheet" href="~/fonts/flaticon/font/flaticon.css">

    <!-- Theme style  -->
    <link rel="stylesheet" href="~/css/style.css">
</head>
<body>
    <header>
        <div id="page">
            <nav class="colorlib-nav" role="navigation">
                <div class="top-menu">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-7 col-md-9">
                                <div id="colorlib-logo"><a asp-area="" asp-controller="Home" asp-action="Index">Hayvan Sahiplenme</a></div>
                            </div>
                            <div class="col-sm-5 col-md-3">
                                <form action="#" class="search-wrap">
                                    <div class="form-group">
                                        <input type="search" class="form-control search" placeholder="Search">
                                        <button class="btn btn-primary submit-search text-center" type="submit"><i class="icon-search"></i></button>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 text-left menu-1">
                                <ul>
                                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Ana Sayfa</a></li>
                                    <li><a asp-area="" asp-controller="Home" asp-action="Ilanlar">İlanlar</a></li>
                                    <li><a asp-area="" asp-controller="Home" asp-action="KopekIlanlari">Köpek İlanları</a></li>
                                    <li><a asp-area="" asp-controller="Home" asp-action="KediIlanlari">Kedi İlanları</></a></li>
                                    @if (User.Identity.IsAuthenticated)
                                    {
                                        if (User.IsInRole("Admin"))
                                        {
                                            <li class="nav-item">
                                                <a asp-area="" asp-controller="Turs" asp-action="Index">Tür</a>
                                            </li>
                                            <li class="nav-item">
                                                <a asp-area="" asp-controller="Cins" asp-action="Index">Cins</a>
                                            </li>
                                        }
                                    }
                                    <partial name="_LoginPartial" />
                                </ul>

                            </div>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>



    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - HayvanSahiplenme - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>